In [1]:
import pandas as pd
import numpy as np
import os
file_path = os.path.abspath(os.path.join('..', 'data', 'quikr_car.csv'))
data = pd.read_csv(file_path)

In [2]:
print(data.shape)
print(data.head())
print(data.info())

(892, 6)
                                     name   company  year          Price  \
0    Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007         80,000
1                 Mahindra Jeep CL550 MDI  Mahindra  2006       4,25,000
2              Maruti Suzuki Alto 800 Vxi    Maruti  2018  Ask For Price
3  Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       3,25,000
4        Ford EcoSport Titanium 1.5L TDCi      Ford  2014       5,75,000

   kms_driven fuel_type
0  45,000 kms    Petrol
1      40 kms    Diesel
2  22,000 kms    Petrol
3  28,000 kms    Petrol
4  36,000 kms    Diesel
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB
None

In [3]:
data['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [4]:
data['Price']=data['Price'].str.replace(',','',regex=False)
data['Price']=pd.to_numeric(data['Price'], errors='coerce')
data = data.dropna(subset=['Price'])
data['Price']=data['Price'].astype(int)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 857 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        857 non-null    object
 1   company     857 non-null    object
 2   year        857 non-null    object
 3   Price       857 non-null    int32
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(1), object(5)
memory usage: 43.5+ KB

In [5]:
data['kms_driven']=data['kms_driven'].str.replace(',','',regex=False)
data['kms_driven']=data['kms_driven'].str.replace('kms','',regex=False)
data['kms_driven'] = pd.to_numeric(data['kms_driven'], errors='coerce')
data = data.dropna(subset=['kms_driven'])
data['kms_driven'] = data['kms_driven'].astype(int)
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    object
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.3+ KB

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel

In [6]:
data=data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 816 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    object
 3   Price       816 non-null    int32
 4   kms_driven  816 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.2+ KB

In [7]:
data['name']=data['name'].str.split(' ').str.slice(0,3).str.join(' ')
data.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6               Ford Figo      Ford  2012  175000       41000    Diesel

In [8]:
data=data.reset_index(drop=True)
data.head()

                     name   company  year   Price  kms_driven fuel_type
0     Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1     Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2       Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3  Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4               Ford Figo      Ford  2012  175000       41000    Diesel

In [9]:
data.describe()

              Price     kms_driven
count  8.160000e+02     816.000000
mean   4.117176e+05   46275.531863
std    4.751844e+05   34297.428044
min    3.000000e+04       0.000000
25%    1.750000e+05   27000.000000
50%    2.999990e+05   41000.000000
75%    4.912500e+05   56818.500000
max    8.500003e+06  400000.000000

In [10]:
data=data[data['Price']<6e6].reset_index(drop=True)
data.info()
#there was one outliner data point

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815 entries, 0 to 814
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        815 non-null    object
 1   company     815 non-null    object
 2   year        815 non-null    object
 3   Price       815 non-null    int32
 4   kms_driven  815 non-null    int32
 5   fuel_type   815 non-null    object
dtypes: int32(2), object(4)
memory usage: 32.0+ KB

In [14]:
BASE_DIR = os.path.abspath(os.path.join(os.getcwd(), ".."))  
data_path = os.path.join(BASE_DIR, "data", "cleaned_quikr_car.csv")

data.to_csv(data_path, index=False)

In [15]:
pd.read_csv(data_path).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815 entries, 0 to 814
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        815 non-null    object
 1   company     815 non-null    object
 2   year        815 non-null    int64
 3   Price       815 non-null    int64
 4   kms_driven  815 non-null    int64
 5   fuel_type   815 non-null    object
dtypes: int64(3), object(3)
memory usage: 38.3+ KB

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score  #to chk accuracy in regression...in classification you can just use accuracy_score()
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import make_pipeline
from sklearn import preprocessing
from sklearn.compose import make_column_transformer

In [ ]:
#first have to encode strings into values so that it can be plotted on graph
oh=OneHotEncoder(handle_unknown='ignore')
oh.fit(x[['company','fuel_type']])
oh.categories_

[array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [ ]:
y=data['Price']
x=data[['company','year','kms_driven','fuel_type']]

In [ ]:
column_trans=make_column_transformer((OneHotEncoder(categories=oh.categories_),['company','fuel_type']),remainder='passthrough')

In [ ]:
score = []
from sklearn.model_selection import train_test_split
epoch = 100
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2,shuffle=True)
print(X_train)
for i in range(epoch):

    reg = LinearRegression()
    pipe = make_pipeline(column_trans, reg)
    pipe.fit(X_train, y_train)

    # Predict on TEST set (not train)
    y_pred = pipe.predict(X_test)

    # Compare y_test and y_pred
    score.append(r2_score(y_test, y_pred))

      company  year  kms_driven fuel_type
498   Hyundai  2016        8000    Petrol
382    Maruti  2013       90000    Diesel
584    Maruti  2012      160000       LPG
79   Mahindra  2013       20000    Diesel
622   Hyundai  2011       42000    Petrol
..        ...   ...         ...       ...
766    Maruti  2000       60000    Petrol
335   Hyundai  2014       23000    Petrol
267    Maruti  2003       56758    Petrol
615   Hyundai  2012       65000    Petrol
725      Ford  2008       46000    Petrol

[652 rows x 4 columns]

In [ ]:
score[np.argmax(score)]

0.6218020834652473

In [ ]:
import pickle

with open('car_price_model.pkl', 'wb') as f:
    pickle.dump(pipe, f)

print("Model saved as car_price_model.pkl")

Model saved as car_price_model.pkl